name: Slack and Gmail Notification on Success or Failure

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a simple task
        id: task
        run: |
          echo "Running a simple task..."
          # Simulate a task; replace with your actual command
          # Uncomment the next line to simulate failure
          # exit 1

      - name: Send Slack Notification
        if: always()  # This ensures the step runs regardless of previous step success or failure
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [ "${{ steps.task.outcome }}" == "success" ]; then
            STATUS="success"
            MESSAGE="The task completed successfully!"
          else
            STATUS="failure"
            MESSAGE="The task failed!"
          fi

          curl -X POST -H 'Content-type: application/json' --data "{
            \"text\": \"Task Status: $STATUS\n$MESSAGE\"
          }" $SLACK_WEBHOOK_URL

      - name: Send Gmail Notification
        if: always()  # This ensures the step runs regardless of previous step success or failure
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
        run: |
          echo "Sending email notification..."
          npm install nodemailer
          node -e "
          const nodemailer = require('nodemailer');

          const transporter = nodemailer.createTransport({
            service: 'gmail',
            auth: {
              user: process.env.GMAIL_USER,
              pass: process.env.GMAIL_PASS,
            },
          });

          const status = '${{ steps.task.outcome }}';
          const message = status === 'success' ? 'The task completed successfully!' : 'The task failed!';

          const mailOptions = {
            from: process.env.GMAIL_USER,
            to: 'recipient@example.com',  // Change this to the recipient's email address
            subject: 'GitHub Actions Notification',
            text: \`Task Status: \${status}\n\${message}\`,
          };

          transporter.sendMail(mailOptions, (error, info) => {
            if (error) {
              console.log('Error:', error);
            } else {
              console.log('Email sent:', info.response);
            }
          });
          "
