name: Echo Success or Failure Notification with Slack

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run echo success or failure
      id: echo_result
      run: |
        echo "Running a task..."
        # Simulate a task. Change the exit code to simulate success or failure.
        # Uncomment one of the following lines to simulate success or failure.
        # exit 0 # Success
        exit 1 # Failure

    - name: Send success notification to Slack
      if: success()
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{"text":"Task succeeded in GitHub Actions!"}' \
        ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Send failure notification to Slack
      if: failure()
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{"text":"Task failed in GitHub Actions!"}' \
        ${{ secrets.SLACK_WEBHOOK_URL }}
